version: "3"

networks:
  spark-network:
    driver: bridge

services:
  spark-master:
    image: apache/spark-py:latest
    container_name: spark-master
    environment:
      - SPARK_CONF_DIR=/opt/spark/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/tmp/spark-events"
    volumes:
      - C:\Users\aerde\spark\conf:/opt/spark/conf
      - C:\Users\aerde\spark\logs:/tmp/spark-events
    networks:
      - spark-network
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark-py:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_CONF_DIR=/opt/spark/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/tmp/spark-events"
    volumes:
      - C:\Users\aerde\spark\conf:/opt/spark/conf
      - C:\Users\aerde\spark\work:/opt/spark/work
      - C:\Users\aerde\spark\logs:/tmp/spark-events
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-history:
    image: apache/spark-py:latest
    container_name: spark-history
    depends_on:
      - spark-master
    environment:
      - SPARK_CONF_DIR=/opt/spark/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/tmp/spark-events"
    volumes:
      - C:\Users\aerde\spark\conf:/opt/spark/conf
      - C:\Users\aerde\spark\logs:/tmp/spark-events
    networks:
      - spark-network
    ports:
      - "18080:18080"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer

  my-pyspark-job:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - spark-master
      - spark-worker
      - spark-history
    command: "/opt/spark/bin/spark-submit --master spark://spark-master:7077 /app/test.py"
    volumes:
      - C:\Users\aerde\spark\conf:/opt/spark/conf
      - C:\Users\aerde\spark\logs:/tmp/spark-events
    networks:
      - spark-network